title = "Adalberto's Dev Config"

[owner]
name = "Adalberto Garcia"

[database]
path = "private/farm-automation-2300f-firebase-adminsdk-m90e8-bdb46acc12.json"
projectId = "farm-automation-2300f"

[moonraker]
baseUrl = "http://localhost:7125/"

[temp]
filename = "gcode/example.gcode"